
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - python setup.py develop
script:
  - cd demo
  - coverage run --source='../sql' manage.py test sql
after_success:
- coveralls
