
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - pip install -r requirements_dev.txt
  - pip install coveralls
  - python setup.py develop
script:
  - cd demo
  - coverage run --source='../sqlapp' manage.py test sqlapp
after_success:
- coveralls
